USE employee_db;

SELECT * FROM roles;
/* JOIN DEPARTMENT AND ROLES */
SELECT * FROM roles
JOIN departments ON roles.department_id = departments.id;
/* JOIN EMPLOYEE W ROLES/DEPARTMENT SEEMINGLY */
/* EMPLOYEE TABLE SHOWS:
    FIRST NAME
    LAST NAME
    JOB TITLE/NAME
    DEPARTMENT
    SALARY
    MANAGER THAT EMPLOYEE REFER TO */